### ISSUE TITLE
Artist page crashed 

### ISSUE THREAD

**Issue by jerryop** [Malopieds/Malo-Musique#21]
@Malopieds I installed your debug app and whenever i click on more of artist page comes but it crashes I saw you implemented a new feature showing all songs of that artist I want to use it but it crashes everytime i click -_-

**Comment by Malopieds** [comment]
The one in the release or in the source code?
Have you loaded a database with it?

**Comment by jerryop** [comment]
> The one in the release or in the source code? Have you loaded a database with it?

In the source code you provided some hours ago

**Comment by Malopieds** [comment]
@jerryop what about the database? Can you send it here please.
Can you join also the logfile please?

**Comment by jerryop** [comment]
> @jerryop what about the database? Can you send it here please. Can you join also the logfile please?

How I can provide database should I do screen recorder and then send here?

**Comment by Malopieds** [comment]
@jerryop Ok, I may have found why, can you try [this apk](https://github.com/Malopieds/Malo-Musique/releases/download/v0.4.5/app-release.apk) (the latest release)

**Comment by jerryop** [comment]
> @jerryop Ok, I may have found why, can you try [this apk](https://github.com/Malopieds/Malo-Musique/releases/download/v0.4.5/app-release.apk) (the latest release)

Check video https://streamable.com/lc2zf1

**Comment by Malopieds** [comment]
I know why it does that, thanks for reporting it.
It's only for some artist. I'll try to add the fix later on the week !

**Comment by jerryop** [comment]
@Malopieds you fixed this issue?

**Comment by Malopieds** [comment]
I kinda know what to, I'll be working on that tonight

**Comment by Malopieds** [comment]
[here](https://github.com/Malopieds/Malo-Musique/releases/tag/v0.4.5-dev) is the new app debug, reopen if it has not fixed your issue but should have.

**Comment by Malopieds** [comment]
I'll reopen it since there is another crash not exactly on the same page. This is mainly for me to remember.
Step to reproduce:
- Visit artist page
- click on show more songs
- slide to the right to play it next ==> crash

**Comment by Malopieds** [comment]
Now fixed.
